name: on release

on:
  release:
    types: [published]

jobs:
  release-laundromat:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Update version
        run: |
          export VERSION=$(echo ${{ github.ref }} | sed "s/refs\/tags\///")
          sed -i "s~version=.*~version='$VERSION',~g" setup.py
      - name: Install twine
        run: pip3 install twine --user
      - name: Build release
        run: python3 setup.py sdist bdist_wheel
      - name: Publish pypi
        run: python -m twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }} dist/*